export default {
    "normal":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/NormalIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/NormalIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":2,
            "flying":1,
            "poison":1,
            "ground":1,
            "rock":1,
            "bug":1,
            "ghost":0,
            "steel":1,
            "fire":1,
            "water":1,
            "grass":1,
            "electric":1,
            "psychic":1,
            "ice":1,
            "dragon":1,
            "dark":1,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "fighting":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/FightingIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/FightingIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":1,
            "flying":2,
            "poison":1,
            "ground":1,
            "rock":0.5,
            "bug":0.5,
            "ghost":1,
            "steel":1,
            "fire":1,
            "water":1,
            "grass":1,
            "electric":1,
            "psychic":2,
            "ice":1,
            "dragon":1,
            "dark":0.5,
            "fairy":2,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "flying":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/FlyingIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/FlyingIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":0.5,
            "flying":1,
            "poison":1,
            "ground":0,
            "rock":2,
            "bug":0.5,
            "ghost":1,
            "steel":1,
            "fire":1,
            "water":1,
            "grass":0.5,
            "electric":2,
            "psychic":1,
            "ice":2,
            "dragon":1,
            "dark":1,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "poison":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/PoisonIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/PoisonIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":0.5,
            "flying":1,
            "poison":0.5,
            "ground":2,
            "rock":1,
            "bug":0.5,
            "ghost":1,
            "steel":1,
            "fire":1,
            "water":1,
            "grass":0.5,
            "electric":1,
            "psychic":2,
            "ice":1,
            "dragon":1,
            "dark":1,
            "fairy":0.5,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "ground":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/GroundIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/GroundIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":1,
            "flying":1,
            "poison":0.5,
            "ground":1,
            "rock":0.5,
            "bug":1,
            "ghost":1,
            "steel":1,
            "fire":1,
            "water":2,
            "grass":2,
            "electric":0,
            "psychic":1,
            "ice":2,
            "dragon":1,
            "dark":1,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "rock":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/RockIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/RockIC.png"
        },
        "effectiveness":{
            "normal":0.5,
            "fighting":2,
            "flying":0.5,
            "poison":0.5,
            "ground":2,
            "rock":1,
            "bug":1,
            "ghost":1,
            "steel":2,
            "fire":0.5,
            "water":2,
            "grass":2,
            "electric":1,
            "psychic":1,
            "ice":1,
            "dragon":1,
            "dark":1,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "bug":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/BugIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/BugIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":0.5,
            "flying":2,
            "poison":1,
            "ground":0.5,
            "rock":2,
            "bug":1,
            "ghost":1,
            "steel":1,
            "fire":2,
            "water":1,
            "grass":0.5,
            "electric":1,
            "psychic":1,
            "ice":1,
            "dragon":1,
            "dark":1,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "ghost":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/GhostIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/GhostIC.png"
        },
        "effectiveness":{
            "normal":0,
            "fighting":0,
            "flying":1,
            "poison":0.5,
            "ground":1,
            "rock":1,
            "bug":0.5,
            "ghost":2,
            "steel":1,
            "fire":1,
            "water":1,
            "grass":1,
            "electric":1,
            "psychic":1,
            "ice":1,
            "dragon":1,
            "dark":2,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "steel":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/SteelIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/SteelIC.png"
        },
        "effectiveness":{
            "normal":0.5,
            "fighting":2,
            "flying":0.5,
            "poison":0,
            "ground":2,
            "rock":0.5,
            "bug":0.5,
            "ghost":1,
            "steel":0.5,
            "fire":2,
            "water":1,
            "grass":0.5,
            "electric":1,
            "psychic":0.5,
            "ice":0.5,
            "dragon":0.5,
            "dark":1,
            "fairy":0.5,
            "nuclear":0.5,
            "shadow": 2,
            "untyped": 1
        }
    },
    "fire":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/FireIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/FireIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":1,
            "flying":1,
            "poison":1,
            "ground":2,
            "rock":2,
            "bug":0.5,
            "ghost":1,
            "steel":0.5,
            "fire":0.5,
            "water":2,
            "grass":0.5,
            "electric":1,
            "psychic":1,
            "ice":0.5,
            "dragon":1,
            "dark":1,
            "fairy":0.5,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "water":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/WaterIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/WaterIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":1,
            "flying":1,
            "poison":1,
            "ground":1,
            "rock":1,
            "bug":1,
            "ghost":1,
            "steel":0.5,
            "fire":0.5,
            "water":0.5,
            "grass":2,
            "electric":2,
            "psychic":1,
            "ice":0.5,
            "dragon":1,
            "dark":1,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "grass":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/GrassIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/GrassIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":1,
            "flying":2,
            "poison":2,
            "ground":0.5,
            "rock":1,
            "bug":2,
            "ghost":1,
            "steel":1,
            "fire":2,
            "water":0.5,
            "grass":0.5,
            "electric":0.5,
            "psychic":1,
            "ice":2,
            "dragon":1,
            "dark":1,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "electric":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/ElectricIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/ElectricIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":1,
            "flying":0.5,
            "poison":1,
            "ground":2,
            "rock":1,
            "bug":1,
            "ghost":1,
            "steel":0.5,
            "fire":1,
            "water":1,
            "grass":1,
            "electric":0.5,
            "psychic":1,
            "ice":1,
            "dragon":1,
            "dark":1,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "psychic":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/PsychicIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/PsychicIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":0.5,
            "flying":1,
            "poison":1,
            "ground":1,
            "rock":1,
            "bug":2,
            "ghost":2,
            "steel":1,
            "fire":1,
            "water":1,
            "grass":1,
            "electric":1,
            "psychic":0.5,
            "ice":1,
            "dragon":1,
            "dark":2,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "ice":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/IceIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/IceIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":2,
            "flying":1,
            "poison":1,
            "ground":1,
            "rock":2,
            "bug":1,
            "ghost":1,
            "steel":2,
            "fire":2,
            "water":1,
            "grass":1,
            "electric":1,
            "psychic":1,
            "ice":0.5,
            "dragon":1,
            "dark":1,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "dragon":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/DragonIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/DragonIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":1,
            "flying":1,
            "poison":1,
            "ground":1,
            "rock":1,
            "bug":1,
            "ghost":1,
            "steel":1,
            "fire":0.5,
            "water":0.5,
            "grass":0.5,
            "electric":0.5,
            "psychic":1,
            "ice":2,
            "dragon":2,
            "dark":1,
            "fairy":2,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "dark":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/DarkIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/DarkIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":2,
            "flying":1,
            "poison":1,
            "ground":1,
            "rock":1,
            "bug":2,
            "ghost":0.5,
            "steel":1,
            "fire":1,
            "water":1,
            "grass":1,
            "electric":1,
            "psychic":0,
            "ice":1,
            "dragon":1,
            "dark":0.5,
            "fairy":2,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "fairy":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/FairyIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/FairyIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":0.5,
            "flying":1,
            "poison":2,
            "ground":1,
            "rock":1,
            "bug":0.5,
            "ghost":1,
            "steel":2,
            "fire":1,
            "water":1,
            "grass":1,
            "electric":1,
            "psychic":1,
            "ice":1,
            "dragon":0,
            "dark":0.5,
            "fairy":1,
            "nuclear":2,
            "shadow": 2,
            "untyped": 1
        }
    },
    "nuclear":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/NuclearIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/NuclearIC.png"
        },
        "effectiveness":{
            "normal":2,
            "fighting":2,
            "flying":2,
            "poison":2,
            "ground":2,
            "rock":2,
            "bug":2,
            "ghost":2,
            "steel":2,
            "fire":2,
            "water":2,
            "grass":2,
            "electric":2,
            "psychic":2,
            "ice":2,
            "dragon":2,
            "dark":2,
            "fairy":2,
            "nuclear":0.5,
            "shadow": 2,
            "untyped": 1
        }
    },
    "shadow":{
        "images":{
            "bar":"systems/ptu/static/css/images/types2/ShadowIC.png",
            "icon":"systems/ptu/static/css/images/types2/ShadowIC_Icon.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":1,
            "flying":1,
            "poison":1,
            "ground":1,
            "rock":1,
            "bug":1,
            "ghost":1,
            "steel":1,
            "fire":1,
            "water":1,
            "grass":1,
            "electric":1,
            "psychic":1,
            "ice":1,
            "dragon":1,
            "dark":1,
            "fairy":1,
            "nuclear":1,
            "shadow":0.5,
            "untyped": 1
        }
    },
    "untyped":{
        "images":{
            "icon":"systems/ptu/static/css/images/types2/UntypedIC_Icon.png",
            "bar":"/systems/ptu/static/css/images/types2/UntypedIC.png"
        },
        "effectiveness":{
            "normal":1,
            "fighting":1,
            "flying":1,
            "poison":1,
            "ground":1,
            "rock":1,
            "bug":1,
            "ghost":1,
            "steel":1,
            "fire":1,
            "water":1,
            "grass":1,
            "electric":1,
            "psychic":1,
            "ice":1,
            "dragon":1,
            "dark":1,
            "fairy":1,
            "nuclear":1,
            "shadow":1,
            "untyped": 1
        }
    }
} as TypeEffectiveness;

export function getTypes() {
    return Object.keys(game.settings.get("ptr2e", "pokemonTypes") as TypeEffectiveness);
}

const SYSTEM_POKEMON_TYPES = ["untyped", "normal", "fire", "water", "electric", "grass", "ice", "fighting", "poison", "ground", "flying", "psychic", "bug", "rock", "ghost", "dragon", "dark", "steel", "fairy", "nuclear", "shadow"] as const;
export type PokemonTypes = typeof SYSTEM_POKEMON_TYPES[number];

export type TypeEffectiveness = {
    [type in PokemonTypes]: {
        images: {
            icon: string;
            bar: string;
        };
        effectiveness: {
            [type in PokemonTypes]: number;
        };
    };
}