name: PTR2e CD

on:
  workflow_run:
    workflows: ["PTR2e CI"]
    types:
      - completed

jobs:
    release:
        runs-on: ubuntu-latest
        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'Stable'

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x

            - name: Build
              run: |
                  npm ci
                  npm run build

            - name: Update Manifest
              run: |
                  SYSTEM_VERSION=$(grep -oP '(?<="version": ")[^"]+' dist/system.json | tr -d '\n')
                  perl -pi -E "s|latest/download/ptr2e\\.zip|download/$SYSTEM_VERSION/ptr2e.zip|" dist/system.json
                  echo "systemVersion=$SYSTEM_VERSION" >> $GITHUB_ENV

            - name: Zip Files
              working-directory: ./dist
              run: zip -r ./ptr2e.zip ./*

            - name: Create Version Release
              id: create_version_release
              uses: ncipollo/release-action@v1
              with:
                  name: ${{ env.systemVersion }}
                  allowUpdates: true
                  draft: false
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: "./dist/system.json,./dist/ptr2e.zip"
                  tag: ${{ env.systemVersion }}
