name: PTR2e CI
on:
    pull_request_review:
        types: [submitted]
    push:
        branches: [Stable]
    workflow_dispatch:
jobs:
    build:
        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x

            - name: Cache NPM Deps
              id: cache-npm
              uses: actions/cache@v3
              with:
                path: node_modules/
                key: npm-${{ hashFiles('package-lock.json') }}

            - name: Install NPM Deps
              if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run tests
              run: npm run test
