name: PTR2e CI
on:
    pull_request:
        branches: [Stable, Staging, Development]
    push:
        branches: [Stable, Staging, Development]
    pull_request_target: 
        branches: [Staging, Development]
        types: [opened, synchronize, reopened, ready_for_review]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x

            - name: Cache NPM Deps
              id: cache-npm
              uses: actions/cache@v3
              with:
                path: node_modules/
                key: npm-${{ hashFiles('package-lock.json') }}

            - name: Install NPM Deps
              if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run tests
              run: npm run test
