name: PTR2e Wiki Sync
on:
    workflow_run:
        workflows: ["PTR2e CD"]
        types:
            - completed
        branches:
            - Stable
    workflow_dispatch:

jobs:
    wiki-sync:
        if: github.event.repository.fork == false && github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x

            - name: Checkout Wiki Git Repo
              uses: actions/checkout@v4
              with:
                  repository: 'pokemon-tabletop-reunited/ptr2e-wiki'
                  path: 'ptr2e-wiki'
                  ref: 'master'
                  token: ${{ secrets.WIKI_PAT }}

            - name: Create Wiki Pages
              run: |
                  npm ci
                  rm -r ptr2e-wiki/data/abilities/**/*.md
                  rm -r ptr2e-wiki/data/items/consumables/**/*.md
                  rm -r ptr2e-wiki/data/items/equipment/**/*.md
                  rm -r ptr2e-wiki/data/items/gear/**/*.md
                  rm -r ptr2e-wiki/data/items/weapons/**/*.md
                  rm -r ptr2e-wiki/data/lists/**/*.md
                  rm -r ptr2e-wiki/data/moves/**/*.md
                  rm -r ptr2e-wiki/data/perks/**/*.md
                  rm -r ptr2e-wiki/data/species/**/*.md
                  rm -r ptr2e-wiki/data/traits/**/*.md
                  npm run sync:wiki

            - name: Git Push Wiki Pages
              run: |
                cd ptr2e-wiki
                git config user.name "Wiki Sync Action"
                git config user.email "ashe@soaringnetwork.com"
                git add .
                git commit -m "Sync Wiki Pages"
                git push
